[2023-12-17T15:14:14.953+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datalake_refresh_dataflow_powerbi.taskRefreshDataflowPowerBI scheduled__2023-12-16T15:14:11.409942+00:00 [queued]>
[2023-12-17T15:14:14.962+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datalake_refresh_dataflow_powerbi.taskRefreshDataflowPowerBI scheduled__2023-12-16T15:14:11.409942+00:00 [queued]>
[2023-12-17T15:14:14.964+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-17T15:14:14.976+0000] {taskinstance.py:1382} INFO - Executing <Task(PowerBIDataflowRefreshOperator): taskRefreshDataflowPowerBI> on 2023-12-16 15:14:11.409942+00:00
[2023-12-17T15:14:14.983+0000] {standard_task_runner.py:57} INFO - Started process 19738 to run task
[2023-12-17T15:14:14.986+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'datalake_refresh_dataflow_powerbi', 'taskRefreshDataflowPowerBI', 'scheduled__2023-12-16T15:14:11.409942+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/powerbi_abandoned/datalake_refresh_dataflow_powerbi.py', '--cfg-path', '/tmp/tmp6bcs0242']
[2023-12-17T15:14:14.989+0000] {standard_task_runner.py:85} INFO - Job 198: Subtask taskRefreshDataflowPowerBI
[2023-12-17T15:14:15.033+0000] {task_command.py:416} INFO - Running <TaskInstance: datalake_refresh_dataflow_powerbi.taskRefreshDataflowPowerBI scheduled__2023-12-16T15:14:11.409942+00:00 [running]> on host 83c86e565932
[2023-12-17T15:14:15.097+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='datalake_refresh_dataflow_powerbi' AIRFLOW_CTX_TASK_ID='taskRefreshDataflowPowerBI' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T15:14:11.409942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-16T15:14:11.409942+00:00'
[2023-12-17T15:14:15.099+0000] {powerbi_dataflow_refresh_operator.py:88} INFO - Calling API Dataflow ID: fdbac82b-4169-4aaf-80c2-1f6cdde56b46
[2023-12-17T15:14:15.100+0000] {logging_mixin.py:154} INFO - Refresh dataflow url: https://api.powerbi.com/v1.0/myorg/datasets/fdbac82b-4169-4aaf-80c2-1f6cdde56b46/refreshes - headers: {'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSIsImtpZCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDIxYjc0NzQtMWU3ZC00MGJhLTk1ZjItNGQ0NWJjZTc2YTJiLyIsImlhdCI6MTcwMjgyNTc1MywibmJmIjoxNzAyODI1NzUzLCJleHAiOjE3MDI4Mjk2NTMsImFpbyI6IkUyVmdZRGphMUhQZFpJcmczUW9SbzVKYnBlY3VBQUE9IiwiYXBwaWQiOiJiZWM0MWFiOC1lMzNhLTRiODMtOTJkNi05ZDJjOTU3Zjk0NGMiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kMjFiNzQ3NC0xZTdkLTQwYmEtOTVmMi00ZDQ1YmNlNzZhMmIvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiJlY2FlZTAyOS00OTczLTQ4MjQtOWU4MS04NDA1Y2RjOGIzMDMiLCJyaCI6IjAuQVhJQWRIUWIwbjBldWtDVjhrMUZ2T2RxS3drQUFBQUFBQUFBd0FBQUFBQUFBQUREQUFBLiIsInN1YiI6ImVjYWVlMDI5LTQ5NzMtNDgyNC05ZTgxLTg0MDVjZGM4YjMwMyIsInRpZCI6ImQyMWI3NDc0LTFlN2QtNDBiYS05NWYyLTRkNDViY2U3NmEyYiIsInV0aSI6ImxWOVMyR3pmcVV1TENDZUZtM0ZvQUEiLCJ2ZXIiOiIxLjAifQ.dHRXio-4XjCEoJ4j2qMQcK-OTAhjRU0Lnd8kCNImd12H0bTClLZn9U8tmnhoDsR0_nNxPVce4EhjDDyJoD2aMl74EaPjWgG3qi6YGg46G9I2pADkdUelUYhPugfDy5KJLgT4oMWvwlg43juUwMn7uG_KipnVI3lX2IePmW1vLFy0i3Kbp-Q4fepfacRNuW-05btGUtS-woh-pMF481zcKgruGrdIM5cTsACR6R7T5ROewuS5W2SHCtE9ZIoYfOAe3EUqexTEWh0yYcHk7Fzsnt3-E0_W-6khbRdjUWTw7kSbzlW-ukrV_fskM0gNKByzkwuWex2vQZa5UbNcn4CUMQ'}
[2023-12-17T15:14:15.101+0000] {powerbi_dataflow_refresh_operator.py:71} INFO - Refresh dataflow url: https://api.powerbi.com/v1.0/myorg/datasets/fdbac82b-4169-4aaf-80c2-1f6cdde56b46/refreshes
[2023-12-17T15:14:16.626+0000] {powerbi_dataflow_refresh_operator.py:84} INFO - status: 401, data: b''
[2023-12-17T15:14:16.628+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/powerbi_dataflow_refresh_operator.py", line 94, in execute
    raise Exception(f"Power BI dataflow refresh failed for Dataflow ID: {self.dataflow_id}")
Exception: Power BI dataflow refresh failed for Dataflow ID: fdbac82b-4169-4aaf-80c2-1f6cdde56b46
[2023-12-17T15:14:16.661+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=datalake_refresh_dataflow_powerbi, task_id=taskRefreshDataflowPowerBI, execution_date=20231216T151411, start_date=20231217T151414, end_date=20231217T151416
[2023-12-17T15:14:16.673+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 198 for task taskRefreshDataflowPowerBI (Power BI dataflow refresh failed for Dataflow ID: fdbac82b-4169-4aaf-80c2-1f6cdde56b46; 19738)
[2023-12-17T15:14:16.690+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-17T15:14:16.707+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
