[2023-12-19T04:21:21.124+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T04:21:20.139493+00:00 [queued]>
[2023-12-19T04:21:21.131+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T04:21:20.139493+00:00 [queued]>
[2023-12-19T04:21:21.132+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-19T04:21:21.141+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): steal_ETL> on 2023-12-19 04:21:20.139493+00:00
[2023-12-19T04:21:21.150+0000] {standard_task_runner.py:57} INFO - Started process 1274 to run task
[2023-12-19T04:21:21.153+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'steal_etl_storeToPostgres', 'steal_ETL', 'manual__2023-12-19T04:21:20.139493+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/steal_etl_storeToPostgres.py', '--cfg-path', '/tmp/tmpg6cbw3cb']
[2023-12-19T04:21:21.155+0000] {standard_task_runner.py:85} INFO - Job 365: Subtask steal_ETL
[2023-12-19T04:21:21.192+0000] {task_command.py:416} INFO - Running <TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T04:21:20.139493+00:00 [running]> on host f97daee24bd9
[2023-12-19T04:21:21.381+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='christinelee1114@gmail.com' AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='steal_etl_storeToPostgres' AIRFLOW_CTX_TASK_ID='steal_ETL' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T04:21:20.139493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-19T04:21:20.139493+00:00'
[2023-12-19T04:21:21.402+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:71: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc.drop('_id', axis=1, inplace=True)

[2023-12-19T04:21:21.403+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:72: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc.rename(columns=newcolumns, inplace=True)

[2023-12-19T04:21:21.404+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/steal_etl_storeToPostgres.py", line 75, in steal_etl
    df_loc['日期'] = str(int(df_loc['年'])+1911)+df_loc['月']+df_loc['日']
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 230, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
[2023-12-19T04:21:21.418+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=steal_etl_storeToPostgres, task_id=steal_ETL, execution_date=20231219T042120, start_date=20231219T042121, end_date=20231219T042121
[2023-12-19T04:21:21.427+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 365 for task steal_ETL (cannot convert the series to <class 'int'>; 1274)
[2023-12-19T04:21:21.446+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-19T04:21:21.588+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
