[2023-12-14T02:12:23.622+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_cctv_data_to_postgresql.send_email_task manual__2023-12-14T02:11:55.933539+00:00 [queued]>
[2023-12-14T02:12:23.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_cctv_data_to_postgresql.send_email_task manual__2023-12-14T02:11:55.933539+00:00 [queued]>
[2023-12-14T02:12:23.632+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T02:12:23.643+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): send_email_task> on 2023-12-14 02:11:55.933539+00:00
[2023-12-14T02:12:23.651+0000] {standard_task_runner.py:57} INFO - Started process 451 to run task
[2023-12-14T02:12:23.653+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'download_cctv_data_to_postgresql', 'send_email_task', 'manual__2023-12-14T02:11:55.933539+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/download_cctv_data_to_postgresql.py', '--cfg-path', '/tmp/tmpa35n6bb1']
[2023-12-14T02:12:23.656+0000] {standard_task_runner.py:85} INFO - Job 334: Subtask send_email_task
[2023-12-14T02:12:23.726+0000] {task_command.py:416} INFO - Running <TaskInstance: download_cctv_data_to_postgresql.send_email_task manual__2023-12-14T02:11:55.933539+00:00 [running]> on host cbe761bfd41f
[2023-12-14T02:12:23.795+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='download_cctv_data_to_postgresql' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T02:11:55.933539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T02:11:55.933539+00:00'
[2023-12-14T02:12:23.805+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-12-14T02:12:23.806+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2023-12-14T02:12:23.807+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-12-14T02:12:23.808+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-12-14T02:12:23.816+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_cctv_data_to_postgresql, task_id=send_email_task, execution_date=20231214T021155, start_date=20231214T021223, end_date=20231214T021223
[2023-12-14T02:12:23.827+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 334 for task send_email_task ([Errno 99] Cannot assign requested address; 451)
[2023-12-14T02:12:23.867+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T02:12:23.889+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
